---
Name: redirectedurls
---

SilverStripe\Control\RequestHandler:
  extensions:
   - SilverStripe\RedirectedURLs\RedirectedURLHandler
SilverStripe\CMS\Controllers\ContentController:
  extensions:
   - SilverStripe\RedirectedURLs\RedirectedURLHandler
SilverStripe\CMS\Controllers\ModelAsController:
  extensions:
   - SilverStripe\RedirectedURLs\RedirectedURLHandler
